munit/src/main/scala/munit/Assertions.scala
munit/src/main/scala/munit/Diff.scala
munit/src/main/scala/munit/FailException.scala
munit/src/main/scala/munit/GenericBeforeEach.scala
munit/src/main/scala/munit/GenericTest.scala
munit/src/main/scala/munit/Lines.scala
munit/src/main/scala/munit/Tag.scala
munit/src/main/scala/munit/TestOptions.scala
munit/src/main/scala/munit/TestValues.scala
tests/src/main/scala/munit/CiOnlyFrameworkSuite.scala
tests/src/main/scala/munit/DiffProductFrameworkSuite.scala
tests/src/main/scala/munit/DuplicateNameFrameworkSuite.scala
tests/src/main/scala/munit/FailFrameworkSuite.scala
tests/src/main/scala/munit/FrameworkTest.scala
tests/src/main/scala/munit/InterceptFrameworkSuite.scala
tests/src/test/scala/munit/FrameworkSuite.scala

* Add missing `intercept` assertion
* Improve framework testing infrastructure
* Add serializable trait where relevant, exceptions may be
serialized by sbt.
* Don't use case class for TestOptions
* Make FlakyFailure extend FailException
* Make FailException support suppressing the stack trace

Fix several quirks based on Metals PR

---

munit/shared/src/main/scala-0.21/munit/internal/MacroCompat.scala
munit/shared/src/main/scala-2/munit/internal/MacroCompat.scala
munit/shared/src/main/scala/munit/internal/console/Lines.scala
tests/shared/src/main/scala/munit/DiffProductFrameworkSuite.scala
tests/shared/src/test/scala/munit/LinesSuite.scala

The way it formatted multiline messages made it hard to read before.
Now, if the message is multiline we put the message after the formatted
source code in order to ensure the `/filename:line` line always appears
in the line above the formatted source.

Add basic test cases for Lines class.

---

.github/workflows/ci.yml
.gitignore
build.sbt
munit-sbt/src/main/scala/munit/MUnitGcpListener.scala
munit-sbt/src/main/scala/munit/MUnitLocalListener.scala
munit-sbt/src/main/scala/munit/MUnitPlugin.scala
munit-sbt/src/main/scala/munit/MUnitReportListener.scala
munit-sbt/src/main/scala/munit/MUnitTestReport.scala
munit-sbt/src/main/scala/munit/MUnitTestsListener.scala
munit/non-jvm/src/main/scala/com/geirsson/junit/JUnitReporter.scala
munit/non-jvm/src/main/scala/com/geirsson/junit/MUnitRunNotifier.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
project/plugins.sbt
tests/shared/src/test/scala/munit/DemoSuite.scala

This commit adds a new sbt-munit plugin that registers a new test
listener that uploads JSON test reports to Google Cloud Storage (when
provided the correct configuration). The end goal is to have a way for
projects to collect valuable data about their testing infrastructure to
answer questions like:
* which test cases are most flaky?
* which tests are slow/fast?
* which tests never fail?
* which tests fail frequently?

Add sbt plugin to upload test reports to Google Cloud

---

.jvmopts
build.sbt
docs/reports.md
munit-docs/src/main/java/munit/docs/StorageProxy.java
munit-docs/src/main/resources/META-INF/services/mdoc.PreModifier
munit-docs/src/main/scala/docs/MUnitModifier.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitGcpListener.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitLocalListener.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitPlugin.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitReportListener.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitReportPlugin.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitTestReport.scala
munit-sbt/src/main/scala/munit/sbtmunit/MUnitTestsListener.scala
project/BuildInfo.scala
website/i18n/en.json
website/sidebars.json

Previously, we were storing test report date in Google Cloud but we were
not rendering the data anywhere. Now, we add a new "Test reports" page
on the website that displays some statistics about the test suite in the
MUnit repo.
Example:
The data is not very interesting at the moment since MUnit has a fairly small test suite.

Add `mdoc:munit` modifier to render test reports on the website.

---

docs/assertions.md
munit/shared/src/main/scala/munit/Assertions.scala
tests/shared/src/main/scala/munit/InterceptFrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

Added a check to existing intercept assertion to (optionally) validate that the expected exception's message matches an expected value.  If no message is given, intercept() works as it does today.
Added documentation for intercept().

Added message check to intercept assertion

---

build.sbt
tests/shared/src/main/scala/munit/SwallowedExceptionSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

Fixes #51. Previously, uncaught exceptions without stack traces did not cause the test fail. This upgrade to the latest junit-interface version fixes the issue and this commit adds a test case to prevent future regressions.

Fix bug where exceptions without stack traces cause test success.

---

.gitignore
build.sbt
docs/tests.md
munit-sbt/src/main/scala/munit/sbtmunit/MUnitReportPlugin.scala
munit/js/src/main/scala/munit/internal/PlatformCompat.scala
munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala
munit/native/src/main/scala/munit/internal/PlatformCompat.scala
munit/non-jvm/src/main/scala/com/geirsson/junit/JUnitReporter.scala
munit/non-jvm/src/main/scala/com/geirsson/junit/JUnitTask.scala
munit/shared/src/main/scala-2.11/munit/internal/FutureCompat.scala
munit/shared/src/main/scala-post-2.11/munit/internal/FutureCompat.scala
munit/shared/src/main/scala/munit/FunSuite.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
munit/shared/src/main/scala/munit/Suite.scala
tests/js/src/test/scala/munit/AsyncJSSuite.scala
tests/jvm/src/test/scala/munit/FutureSuite.scala
tests/shared/src/main/scala/munit/FixtureFrameworkSuite.scala
tests/shared/src/main/scala/munit/TestingConsole.scala
tests/shared/src/test/scala/munit/BaseFrameworkSuite.scala
tests/shared/src/test/scala/munit/BaseSuite.scala
tests/shared/src/test/scala/munit/LazyFutureSuite.scala
tests/shared/src/test/scala/munit/TestLocalFixtureSuite.scala
website/blog/2020-02-01-hello-world.md
website/i18n/en.json

Previously, we didn't really support properly async tests. While we were
able to work around this limitation on the JVM with blocking operations,
it made MUnit mostly unusable with Scala.js.  Now, the evaluation of
test cases has been changed so that test evaluation is encoded as a
`Future[Any]` allowing the Scala.js test runner to block until all tests
are finished.
It requires a fairly breaking change in the public API of `FunSuite` to
support truly async tests. The `TestValue` type parameter has changed
from `Any` to `Future[Any]` and the same change has been reflected in
most signatures of methods that users may override such as
`munitRunTest`. I'm quite happy with these breking changes since I found
it much easier to reason about custom modifiers like `.fail` and
`.flaky` when the …

Support truly async Scala.js test

---

munit/shared/src/main/scala/munit/MUnitRunner.scala

Fixes #47. Previously, the `getDescription` method performed
side-effects adding all the test cases as children to the suite
description. When a client such as IntelliJ called `getDescription`
repeated times then it appeared as if the same test started multiple
times in the IntelliJ UI.

Fix bug where test cases got reported as duplicates in IntelliJ.

---

munit/shared/src/main/scala/munit/FunSuite.scala

This overload is not necessary since we already have an implicit
conversion in scope. However, by adding the overload users won't have to
understand implicit conversions to use MUnit in the common case.

Add method overload to `test` helper for easier readability.

---

docs/assertions.md
munit/shared/src/main/scala-2/munit/internal/MacroCompat.scala
munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala
munit/shared/src/main/scala/munit/Assertions.scala
tests/shared/src/test/scala/munit/TypeCheckSuite.scala
website/i18n/en.json

Fixes #36. Previously, it was not possible to write assertions that a
given program does not compile. Now, users can call the
`compileErrors(String): String` macro which takes a string literal as an
argument and returns the compile-time errors as strings (or
empty string if there is no error)
The macro is implemented for both Scala 2.x and Dotty.

Add assertions for compile-time errors

---

munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/FailSuiteException.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/FailSuiteFrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

Fixes #37. Previously, it was possible to abort an individual test case based on a dynamic condition but it was not possible to abort the entire test suite. Now, users can call `failSuite("abort test suite!")` to prevent subsequent test cases from starting.

 Add failSuite() helper to abort the entire test suite

---

munit/shared/src/main/scala/munit/FunSuite.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
website/blog/2020-02-01-hello-world.md

Previously, the "rich filtering capabilities" examples from the initial
MUnit release announcement for v0.3 did not work as expected because of
the async changes in v0.5. This commit fixes the example and improves
the handling of tests with the Ignore tag.

Fix buggy filtering examples from blog post.

---

docs/tests.md
munit/shared/src/main/scala/munit/FunFixtures.scala
munit/shared/src/main/scala/munit/FunSuite.scala
munit/shared/src/main/scala/munit/GenericTest.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
munit/shared/src/main/scala/munit/SuiteTransforms.scala
munit/shared/src/main/scala/munit/TestTransforms.scala
munit/shared/src/main/scala/munit/ValueTransforms.scala
tests/shared/src/main/scala/munit/ScalaVersionFrameworkSuite.scala
tests/shared/src/main/scala/munit/SuiteTransformCrashFrameworkSuite.scala
tests/shared/src/main/scala/munit/SuiteTransformFrameworkSuite.scala
tests/shared/src/main/scala/munit/TestTransformCrashFrameworkSuite.scala
tests/shared/src/main/scala/munit/TestTransformFrameworkSuite.scala
tests/shared/src/main/scala/munit/ValueTransformCrashFrameworkSuite.scala
tests/shared/src/main/scala/munit/ValueTransformFrameworkSuite.scala
tests/shared/src/test/scala/munit/BaseSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala
tests/shared/src/test/scala/munit/LazyFutureSuite.scala
website/blog/2020-02-01-hello-world.md

Opening this as an alternative proposal to #61 (cc/ @kubukoz).
Previously, users could override several methods to customize how tests
were transformed, how suites filtered tests and how values got lifted
into futures. While this system worked OK, it wasn't easy to explain
since it was quite inconsistent.
Now, this commit introduces three consistent solutions to transform:
* test cases: a function `Test => Test`
* test suites: a function `List[Test] => List[Test]`
* test values: a partial function `Any => Future[Any]`
Users register new transforms using a similar API as you register fixtures:
```scala
override def munitTestTransforms: List[TestTransform] =
super.munitTestTransforms ++ List(
new TestTransform("append scala version", { test =>
test.withName(test.name + "-" + scalaVersion) …
```

Use consistent solution to customize tests, suites and values

---

.gitattributes
.github/workflows/ci.yml
.jvmopts
.scalafmt.conf
docs/assertions.md
munit/js/src/main/scala/munit/internal/JSIO.scala
munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/GenericTest.scala
munit/shared/src/main/scala/munit/Printable.scala
munit/shared/src/main/scala/munit/Printer.scala
munit/shared/src/main/scala/munit/Suite.scala
munit/shared/src/main/scala/munit/TestOptions.scala
munit/shared/src/main/scala/munit/TestValues.scala
tests/shared/src/test/scala/munit/AssertionsSuite.scala

Following up from an offline conversation with @gabro
Previously, `assertEquals` only allowed comparing values of the same
type. Now, it's OK as long as the second argument is a subtype of the
first argument. The reasoning for this change is that it's common that
you want to test some generic value like `Option[Int]` obtained from a
method we're testing against an expected hardcoded value like
`Some[Int]`.

Relax `assertEquals` strictness about type equality.

---

build.sbt
munit-scalacheck/shared/src/main/scala/munit/scalacheck/ScalaCheckFailException.scala
munit-scalacheck/shared/src/main/scala/munit/scalacheck/ScalaCheckSuite.scala
tests/shared/src/main/scala/munit/scalacheck/ScalaCheckFrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

This PR adds a new `munit-scalacheck` module which provides a basic level of integration with ScalaCheck via `ScalaCheckSuite`.
Example usage:
```scala
class ScalaCheckFrameworkSuite extends ScalaCheckSuite {
property("list concatenation") {
forAll { (l1: List[Int], l2: List[Int]) =>
l1.size + l2.size == (l1 ::: l2).size
}
}
property("squared") {
forAll { (n: Int) =>
scala.math.sqrt(n * n) == n
}
}
}
```
Example output:
```
munit.scalacheck.ScalaCheckFrameworkSuite:
OK, passed 100 tests.
+ list concatenation 0.454s
==> X munit.scalacheck.ScalaCheckFrameworkSuite.squared  0.03s java.lang.Exception: 
Falsified after 0 passed tests.
> ARG_0: -1
> ARG_0_ORIGINAL: 2147483647
```

Add munit-scalacheck module

---

build.sbt

Oversight from #71. The module has been published as `munitscalacheck` because I've forgotten to specify `moduleName`.

Fix munit-scalacheck module name

---

build.sbt
docs/integrations/scalacheck.md
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckFailException.scala
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckFrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala
website/i18n/en.json
website/sidebars.json

Move ScalaCheck integration into the toplevel package and add documentation

---

docs/integrations/scalacheck.md
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckFrameworkSuite.scala

Previously we only supported writing ScalaCheck properties using boolean expressions (the default ScalaCheck API).
Now we also allow using MUnit assertions in ScalaCheck properties.

Allow using MUnit assertions in ScalaCheck props

---

docs/integrations/scalacheck.md
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckFrameworkSuite.scala

Previously we would not print seeds when a property would fail, so it would be impossible to deterministically reproduce a failure.
Now we print the seed when a property fails and we added docs to explain how to reproduce failures

Print property seeds and add docs about reproducing test failures

---

munit/shared/src/main/scala/munit/internal/console/AnsiColors.scala

Fixes https://github.com/scalameta/munit/issues/108

Use `StringBuilder` in `AnsiColors`

---

build.sbt
docs/getting-started.md
tests/shared/src/test/scala/munit/TypeCheckSuite.scala

Previously, we only built against the latest Dotty release candidate. Now, we
build against both the release candidate and the latest stable release.

Add support for Dotty 0.23.0

---

munit/non-jvm/src/main/scala/org/junit/runner/Runner.scala

When the libraries `scalajs-test-interface` and `scalajs-junit-test-runtime` are placed before MUnit in the classpath, the following linking error occurs:
```
org.junit.runner.Runner (of kind Class) is not a valid interface
implemented by munit.MUnitRunner (of kind Class)
```
Solve this by defining an `abstract class` instead of a `trait` to match JUnit's [`Runner`](https://junit.org/junit4/javadoc/4.12/org/junit/runner/Runner.html).
See also #114.

Runner: Fix Scala.js linking error

---

munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/test/scala/munit/ScalaCheckSeedSuite.scala

Fixes #118 
This is extreme subtle, but it seems to work now

Regenerate default seed at every prop iteration

---

docs/integrations/scalacheck.md
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckExceptionFrameworkSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckFrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

Previously, stack traces from unexpected exceptions would be swallowed
in ScalaCheckSuite. Now, the stack trace is displayed making it easier
to troubleshoot a test failure.
Unexpected exceptions look like this now
Fixes #128

Preserve stack trace of unexpected exceptions in ScalaCheckSuite

---

junit-interface/src/main/java/munit/internal/junitinterface/EventDispatcher.java
junit-interface/src/main/java/munit/internal/junitinterface/RunSettings.java
munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/DuplicateNameFrameworkSuite.scala

A bug in the JUnit/sbt event handler made it ignore tests when two tests
had the same name AND the name contains a `[` character. This bug is a
relic from the original sbt/junit-interface implementation that assumes
that test names are JVM method names where `[` has special meaning.
This bug was not present in the Scala.js implementation.

Fix #138 - duplicate names with bracket characters

---

docs/scalatest.md

With this in place, I think MUnit's documentation captures everything I learned during the conversion. I wonder, though, whether it would be worthwhile to make this page a little more self-contained, i.e. what about linking back to other parts of the documentation that are relevant? Part of the reason I say this is because when a teammate of mine original saw this page, he remarked that it was rather sparse. Perhaps it would be nice to be able to have people go straight to a page on converting, and from there be guided to the other parts of the documentation that they should read. If folks like this idea, I can submit another PR against this page with links to other part of the documentation that I found especially necessary during the conversion.

doc: add a few tips on converting from match-style assertions

---

junit-interface/src/main/java/munit/internal/junitinterface/JUnitComputer.java
junit-interface/src/main/java/munit/internal/junitinterface/PantsFramework.java

Previously, MUnit's `PantsFramework` would look for ScalaTest's JUnit
runner only in `org.scalatest.junit.JUnitRunner`. In ScalaTest 3.1+,
this class has been moved to `org.scalatestplus.junit.JUnitRunner`.
This commit adds a new Fingerprint to the `PantsFramework`, so that
tests defined with ScalaTest 3.1+ can be detected.

Support ScalaTest 3.1+ in `PantsFramework`

---

munit/shared/src/main/scala/munit/FunFixtures.scala
munit/shared/src/main/scala/munit/FunSuite.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
munit/shared/src/main/scala/munit/TestOptions.scala
munit/shared/src/main/scala/munit/internal/difflib/Diff.scala
tests/shared/src/test/scala/munit/BaseFrameworkSuite.scala
tests/shared/src/test/scala/munit/LinesSuite.scala

Fixes #183. Previously, Dotty reported a warning by default when using
functional fixtures because an implicit conversion was triggered. Now,
the warning is no longer reported since there is a method overload for
the common case where the argument is a string literal.

Add method overload to avoid warning in FunFixture.

---

docs/scalatest.md

* Link back to relevant information elsewhere in the docs
* Add tactical tips
* Explain differences in `build.sbt` between MUnit and ScalaTest
* Add some structure to the now-copious information
Hopefully this will encourage adoption!
Note that I was not able to test locally; I could not get the build running. I want to to test that the headers looked okay, and that the links worked. However, I was fairly careful about putting in the links, so I expect it should be fine. If you are at all nervous about it, you may want to render it and see if it is okay.

doc: flesh out the conversion to ScalaTest docs a good deal

---

munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/test/scala/munit/ScalaCheckInitialSeedSuite.scala
tests/shared/src/test/scala/munit/ScalaCheckSeedSuite.scala

Failing seed reporting seems to be incorrect when `scalaCheckInitialSeed` is not overridden. In that case `def seed` would use `def scalaCheckInitialSeed: String = Seed.random().toBase64` and be different every time. Hence the 2 seeds seen here are actually not the ones causing test failure.
https://travis-ci.org/github/spotify/magnolify/jobs/708925430#L369
```
Failing seed: z9omj4mAsT7BcJQoh95CcofqurdkO_jIAGEWFPx7xZA=
You can reproduce this failure by adding the following override to your suite:
override val scalaCheckInitialSeed = "5E72c0hWZ5ioOvDIj2udNT9KuVs1mGz8EBcV-3zyKgH="
```

Report accurate ScalaCheck seed on failing test

---

docs/filtering.md

Seems the checks were failing due to the imports being after some of the usages.

Fix CI checks

---

munit-scalacheck/shared/src/main/scala/munit/ScalaCheckFailException.scala
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
munit/native/src/main/scala/org/junit/ComparisonFailure.scala
munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/ComparisonFailException.scala
munit/shared/src/main/scala/munit/FailException.scala
munit/shared/src/main/scala/munit/FailExceptionLike.scala
munit/shared/src/main/scala/munit/internal/console/Lines.scala
munit/shared/src/main/scala/munit/internal/difflib/ComparisonFailExceptionHandler.scala
munit/shared/src/main/scala/munit/internal/difflib/Diffs.scala
tests/shared/src/main/scala/munit/StackTraceFrameworkSuite.scala
tests/shared/src/test/scala/munit/BaseSuite.scala
tests/shared/src/test/scala/munit/ComparisonFailExceptionSuite.scala
tests/shared/src/test/scala/munit/FailExceptionSuite.scala

Previously, MUnit only supported failing tests with "fail(message)".
Now, users can optionally use the new `failComparison(message, obtained,
expected)` method. This method throws a
`munit.ComparisonFailException`, which is recognised by IntelliJ's JUnit
runner making it possible to view the difference between the
obtained/expected values in a custom GUI diff window.

Introduce a new "failComparison()" helper

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt

Scalacheck is natively built for Dotty.
Since 1.15.0 (and other releases in the 1.15.x series) are binary compatible to 1.14.0, the transition should be smooth.
~1.15.0 final should follow after RC1 next week. I've opened this PR with the RC to figure out if there are any remaining issues with it.~

ScalaCheck 1.15.0

---

bin/test-release.sh
build.sbt
docs/getting-started.md
tests/shared/src/test/scala/munit/BaseSuite.scala

Connected to https://github.com/scalameta/munit/issues/240
Seems we are no longer getting RC versions, so I reverted back to having single stable Dotty version.

Update Scala 3 version to 3.0.0-M1

---

.github/workflows/ci.yml
.github/workflows/release.yml
build.sbt
docs/getting-started.md
munit/js/src/main/scala/munit/internal/JSIO.scala
munit/non-jvm/src/main/scala/munit/internal/junitinterface/IncludeFilter.scala
munit/non-jvm/src/main/scala/munit/internal/junitinterface/JUnitFramework.scala
munit/non-jvm/src/main/scala/munit/internal/junitinterface/Settings.scala
munit/non-jvm/src/main/scala/munit/internal/junitinterface/Tag.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
project/plugins.sbt

Drop Scala.js 0.6.x and enable DottyJS for 3.0.0-M1.
I haven't enabled DottyJS for 0.27 because tests are somehow failing there.
Should help fix #199. Obsoletes #246.

enable DottyJS, drop Scala.js 0.6.x

---

.dependabot.yml
.github/workflows/ci.yml
.github/workflows/release.yml

This PR updates the setup-scala action to v10, which fixes the CI error seen on https://github.com/scalameta/munit/pull/255/checks
It also adds a dependabot configuration that will keep actions up-to-date

Fix the CI and configure dependabot to keep actions updated

---

.github/workflows/ci.yml
tests/shared/src/test/scala/munit/BaseSuite.scala
tests/shared/src/test/scala/munit/LinesSuite.scala

Previously, the CI ran Scalafix but without the --check flag so it
didn't fail the build if there were unused imports.

Check with Scalafix in CI.

---

munit/shared/src/main/scala/munit/internal/console/Printers.scala
tests/shared/src/test/scala/munit/PrintersSuite.scala

Previously, MUnit escaped single quotes inside strings. The escaping is
only needed for single-quote characters.

Fix bug related to escaping single quotes inside strings.

---

munit/shared/src/main/scala/munit/MUnitRunner.scala
munit/shared/src/main/scala/munit/internal/console/Printers.scala
tests/shared/src/main/scala/munit/TestNameFrameworkSuite.scala

Previously, test reports didn't properly escape characters like
carriage returns \r in test names. This commit fixes this bug
for \r along with several other categories of characters that
benefit from escaping.

Fix #258 - escape "non-visible" characters in test names.

---

build.sbt
munit/shared/src/main/scala-2/munit/internal/MacroCompat.scala
munit/shared/src/main/scala-3.0.0-M2/munit/internal/MacroCompat.scala
munit/shared/src/main/scala-3.0.0-M3/munit/internal/MacroCompat.scala
munit/shared/src/main/scala/munit/internal/MacroCompatScala2.scala
munit/shared/src/main/scala/munit/internal/console/Printers.scala
website/blog/2021-01-05-macromix.md

With this change, Scala 2.13 users will be able to depend on munit_3.0
artifacts instead of munit_2.13.
I wasn't able to manually test this change because MUnit doesn't
cross-build for 3.0.0-M1, which is the latest version supported by the
`-Ytasty-reader` flag in 2.13.4. Once 2.13.5 is out, it will be easier
ot make use of this feature.

Mix Scala 2 macros in MUnit Scala 3 module

---

build.sbt
project/plugins.sbt

It seems that the release is failing due to the changes in mdoc I did where we now release:
`mdoc_2.11`, `mdoc_2.12.12`, `mdoc_2.12` and `mdoc_2.13`, where `mdoc_2.12.12` was added to support Scala versions prior to 2.12.13 due to binary incompatibility.
Somehow when using Scala 2.12.11 it actually needs `mdoc-runtime_2.12.11`, which seems to be a bug in coursier. I reported it here: https://github.com/sbt/sbt/issues/6269
This fixes the issue, but I need to investigate a bit further and will try to work around it in mdoc.

Update Scala versions to 2.12.13 and 2.13.4

---

bin/test-release.sh
build.sbt
docs/getting-started.md
munit/native/src/main/scala/munit/internal/PlatformCompat.scala
project/plugins.sbt

Blocked by Scalacheck support https://github.com/typelevel/scalacheck/pull/751

Add support for Scala Native 0.4.0 and cross-publish native for 2.11/2.12/2.13

---

docs/filtering.md

I've changed the include/exclude categories example to be `*-categories=` instead of `*-category=`, to match https://github.com/scalameta/munit/blob/main/junit-interface/src/main/java/munit/internal/junitinterface/JUnitRunner.java#L68.

Fix include/exclude categories arguments in docs

---

bin/test-release.sh
build.sbt
tests/shared/src/test/scala/munit/ClueSuite.scala
tests/shared/src/test/scala/munit/TypeCheckSuite.scala

Closes #350 
Also removes 3.0.0-RC1 support /cc @tgodzik 
I've also re-enabled 2 out of 3 tests that were ignored on Scala 3, since they pass now 🎉

Release for Scala 3.0.0-RC3

---

build.sbt
docs/getting-started.md

It's not out yet, but since it may be this week, I figured we could use some head start 😅

Scala 3.0.0

---

build.sbt
munit/js/src/main/scala/java/io/File.scala
munit/js/src/main/scala/java/nio/file/Files.scala
munit/js/src/main/scala/munit/internal/JSIO.scala
munit/js/src/main/scala/munit/internal/NodeNIOPath.scala

Previously, it was not possible to use MUnit with browser-based
JavaScript environments because MUnit imported the Node.js `fs` module.
This commit refactors the code so that MUnit should gracefully recover
when the Node.js `fs` module is not available.
Fixes #247

Remove Node.js requirement with Scala.js

---

munit/shared/src/main/scala/munit/Assertions.scala
tests/shared/src/test/scala/munit/AssertionsSuite.scala

Improve error message when comparing arrays with same elements

---

build.sbt
docs/tests.md
junit-interface/src/main/java/munit/internal/junitinterface/EventDispatcher.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitRunner.java
junit-interface/src/main/java/munit/internal/junitinterface/RichLogger.java
junit-interface/src/main/java/munit/internal/junitinterface/RunSettings.java

This is the original commit which adds the new `+b` flag, plus a small bugfix and documentation.
IMHO the section "Run tests in parallel" should be on the Getting Started page, which focuses on running tests, and not on the page which focuses on writing tests. If you agree, I'm happy to make that change, too.
This PR does not contain any possible refactoring/simplification we discussed, as that would be better done with a separate PR.

Add buffered logging option

---

docs/tests.md
junit-interface/src/main/java/munit/internal/junitinterface/JUnitRunner.java

Also adjusts the docs accordingly.

Turn on buffered logging by default

---

junit-interface/src/main/java/munit/internal/junitinterface/EventDispatcher.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitTask.java

Previously, buffered logs would sometimes not get flushed resulting in
lost test report output. See #408. This commit adds an extra attempt to
flush the buffered logs inside the sbt testing framework in case the
logs don't get flushed by the JUnit test listener. I'm not 100% sure
this fixes the problem but it seems worth a short and it shouldn't cause
a regression.

Attempt 1: make sure to always flush buffered logs

---

build.sbt

Scala.js and Scala Native Sbt plugins already provide the versions for
the Sbt build to consume.

Use provided `scalaJSVersion` and `nativeVersion`

---

munit/shared/src/main/scala/munit/Assertions.scala
tests/shared/src/main/scala/munit/AssertionsFrameworkSuite.scala

The current logic may claim values have the same `toString()`
when they don't. The 'full' solution would of course be to
have a 'strict' string diff, but until then let's at least
not lie about it.
Fixes #152

More correct string inequality error message

---

build.sbt
munit/shared/src/main/scala/munit/FunFixtures.scala
munit/shared/src/main/scala/munit/FunSuite.scala
munit/shared/src/main/scala/munit/SuiteTransforms.scala
munit/shared/src/main/scala/munit/TestTransforms.scala
munit/shared/src/main/scala/munit/ValueTransforms.scala

Fixes #288. This change allows test suites to extend another class while
bringing in all the functionality of `FunSuite`.

Introduce `BaseFunSuite` trait and make `FunSuite` an empty class

---

docs/getting-started.md

I can confirm this is no longer necessary as of #376.
Following up on #431.

Remove Scala.js-specific instructions

---

junit-interface/src/main/java/munit/internal/junitinterface/AbstractEvent.java
junit-interface/src/main/java/munit/internal/junitinterface/Ansi.java
junit-interface/src/main/java/munit/internal/junitinterface/Configurable.java
junit-interface/src/main/java/munit/internal/junitinterface/CustomFingerprint.java
junit-interface/src/main/java/munit/internal/junitinterface/CustomRunners.java
junit-interface/src/main/java/munit/internal/junitinterface/CustomSuperclasses.java
junit-interface/src/main/java/munit/internal/junitinterface/EmptyRunner.java
junit-interface/src/main/java/munit/internal/junitinterface/EventDispatcher.java
junit-interface/src/main/java/munit/internal/junitinterface/GlobFilter.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnit3Fingerprint.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitComputer.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitFingerprint.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitFramework.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitRunner.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitRunnerWrapper.java
junit-interface/src/main/java/munit/internal/junitinterface/JUnitTask.java
junit-interface/src/main/java/munit/internal/junitinterface/PantsFramework.java
junit-interface/src/main/java/munit/internal/junitinterface/RichLogger.java
junit-interface/src/main/java/munit/internal/junitinterface/RunSettings.java
junit-interface/src/main/java/munit/internal/junitinterface/RunStatistics.java
junit-interface/src/main/java/munit/internal/junitinterface/RunWithFingerprint.java
junit-interface/src/main/java/munit/internal/junitinterface/Settings.java
junit-interface/src/main/java/munit/internal/junitinterface/SilentFilterRequest.java
junit-interface/src/main/java/munit/internal/junitinterface/Tag.java
junit-interface/src/main/java/munit/internal/junitinterface/TagFilter.java
junit-interface/src/main/java/munit/internal/junitinterface/TaskDefFilter.java
junit-interface/src/main/java/munit/internal/junitinterface/TestFilter.java
munit/jvm/src/main/java/munit/IgnoreSuite.java
project/plugins.sbt
tests/shared/src/main/scala/munit/Issue285FrameworkSuite.scala

Previously, we didn't use any code formatter for the Java sources in this project. This PR adds google-java-format so that we have a similar formatting setup for Java as we do for Scala.

Enable google-java-format for Java files

---

.jvmopts

This causes JDK 17 to crash on my machine.

Remove `-XX:+CMSClassUnloadingEnabled` from .jvmopts

---

munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
munit/non-jvm/src/main/scala/munit/internal/junitinterface/MUnitRunNotifier.scala
tests/shared/src/main/scala/munit/ScalaCheckFrameworkSuite.scala

Previously, the Scalacheck suite transform was registered after the
`.flaky` transform so a flaky test would fail even if it was OK to
ignore flaky failures. Reordering the transforms fixes the issue.

Make flaky tag work with Scalacheck suites

---

junit-interface/src/main/java/munit/internal/junitinterface/JUnitRunner.java
junit-interface/src/main/java/munit/internal/junitinterface/RunSettings.java
tests/jvm/src/test/scala/munit/TestSelectorSuite.scala

`TestSelector` can be used to create `TaskDef` which should only execute selected tests from the given test class.
More info can be found at https://github.com/sbt/junit-interface/pull/108 (the changes are almost the same)
~Could you point me how to add a test for that feature and for compatibility?~
That was a silly question, I've already done tests for this in Junit, why not use them here as well.
tl;dr why
This will allow Metals to run a single munit test from the whole suite.

feat: take into account TaskDefs with only TestSelectors.

---

munit/shared/src/main/scala/munit/internal/difflib/Diffs.scala
tests/shared/src/test/scala/munit/ComparisonFailExceptionSuite.scala

Previously, when one used `assertNoDiff` and obtained string was empty there was no clue what does `expected` looks like. Because of that, sometimes it wasn't clear which comparison fails.
Now, in the case when `obtained` is empty, `expected` is being printed.

feat: better "obtained empty" help message

---

build.sbt

Updates
org.scala-lang:scala-library
org.scala-lang:scala-reflect
from 2.13.6 to 2.13.8.
Supersedes https://github.com/scalameta/munit/pull/481 instead of rebasing it

Update Scala213 to 2.13.8

---

.scalafmt.conf
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
munit/shared/src/main/scala/munit/Location.scala

This PR updates scalafmt from 2.7.5 to 3.5.1
I have tried to set things up to have a minimal diff from the previous settings but two minor changes still exist.

Update scalafmt to 3.5.1

---

.scalafmt.conf
munit/shared/src/main/scala-2/munit/internal/MacroCompat.scala
munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala

This was originally in https://github.com/scalameta/munit/pull/225 which I am trying to minimize by plucking things out of it.
This PR updates scalafmt to the latest "3.5.4", and formats the scala-3 MacroCompat files which were previously excluded.
Additionally, this formats `munit/shared/src/main/scala-2/munit/internal/MacroCompat.scala` as the previous regex actually matches on `scala-`

Format scala-3 MacroCompat with scala3 runner

---

build.sbt
project/plugins.sbt

Closes https://github.com/scalameta/munit/pull/550
Closes https://github.com/scalameta/munit/pull/537
Follows https://github.com/scalameta/munit/pull/513#issuecomment-1095413509
As of `sbt-scalafix` 0.10.0, scala version is no longer overriden by `scalafixEnable`, so running with `++2.12.10` would result in "type nowarn is not a member of package annotation" as `nowarn` was introduced in 2.12.13 and sbt macros generate code that uses it.
```
[error] /home/runner/work/munit/munit/munit-sbt/src/main/scala/munit/sbtmunit/MUnitPlugin.scala:42:21: type nowarn is not a member of package annotation
[error]     munitBucketName := Some("munit-test-reports"),
```

scalafix 0.10.1

---

docs/integrations/scalacheck.md
munit-scalacheck/shared/src/main/scala/munit/ScalaCheckSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckExceptionFrameworkSuite.scala
tests/shared/src/main/scala/munit/ScalaCheckFrameworkSuite.scala

Fixes https://github.com/scalameta/munit/issues/563

Use `def` to override `scalaCheckInitialSeed`

---

munit/shared/src/main/scala/munit/MUnitRunner.scala

This moves down `notifier.fireTestStarted(description)` to only apply when a test is NOT ignored. This will not also follow the `org.junit.runner.notification.RunNotifier` contract but also unblock people in Gradle to use their enterprise features 
I wonder if this could be added to a potential v1.0.0-M7
Here is a build scan that shows the tests working now in Gradle with this change https://scans.gradle.com/s/t2og6zyoc3nzc/tests/overview

MUnitRunner: avoid invoking fireTestStarted if a test is skipped. 

---

munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala

Fixes #540.
Based on comment https://github.com/scalameta/munit/issues/540#issuecomment-1318675863

Use daemon thread instead of non-daemon thread which prevent JVM from exiting

---

junit-interface/src/main/java/munit/internal/junitinterface/EventDispatcher.java
munit/native/src/main/scala/org/junit/AssumptionViolatedException.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/SkippedFrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

`assume(false)` gets now handled in the same way as `test("description".ignore")`. Added tests to cover both ways to skip tests.
Fixes #614

Handle assume(false) correctly

---

.github/workflows/ci.yml
.github/workflows/release.yml

* olafurpg/setup got deprecated in https://github.com/olafurpg/setup-scala/releases/tag/v14
* replaced by [actions/setup-java@v3](https://github.com/actions/setup-java)
* enabled sbt caching
* olafurpg/setup-gpg is no longer required since [sbt-ci-release v1.5.5](https://github.com/sbt/sbt-ci-release/releases/tag/v1.5.5)

Update github workflows

---

docs/tests.md
munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/Printer.scala
tests/shared/src/test/scala/munit/CustomPrinterSuite.scala

Hi ! 
Following this issue I opened https://github.com/scalameta/munit/issues/637 and closed right after once I realised I should havve looked around a bit more, I tried my hand at using custom pretty printers to clarify some of my diffs. 
Using the answer to this question https://github.com/scalameta/munit/issues/480 I got pretty much what a I needed ( comparing scodecs ByteVectors ) but I found the experience a bit confusing and felt some boilerplate could be avoided.
Which leads me to this PR :) 
Changes : 
- add `orElse` combinator for `Printer` for composability
- add utility constructor for easier instantiation : user will only pass whatever is actually meaningful to them in most cases, ie. the custom logic to turn their test values into differenciable strings
- update `Assertion` …

feat(printer): mk printers more easily configurable

---

munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/Issue583FrameworkSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

if they are happening inside a test
I only execute the test on the JVM, because
- on JS the error message is different
- on Native the runner just terminates (I know too little about ScalaNative)
Fixes #583

Handle a StackOverflowError in addition to NonFatal errors

---

docs/scalatest.md

I'm told this step isn't needed any more

Remove outdated doc instruction

---

munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/SwallowedExceptionSuite.scala

In case of any Throwable inside a test mark the test as failed.

---

munit/native/src/main/scala/munit/internal/PlatformCompat.scala

I'm surprised that this was missing and nobody noticed for so long. Every other test framework does this, it's absolutely essential.
Fixes https://github.com/scalameta/munit/issues/692.

Call `scalanative.runtime.loop()`

---

junit-interface/src/main/java/munit/internal/junitinterface/Ansi.java
munit/js-native/src/main/scala/munit/internal/junitinterface/JUnitReporter.scala
munit/shared/src/main/scala/munit/internal/console/AnsiColors.scala
munit/shared/src/main/scala/munit/internal/console/Lines.scala
munit/shared/src/main/scala/munit/internal/difflib/Diff.scala

As per https://no-color.org/ this change will disable ANSI colors if the NO_COLOR environment variable is set to any non-empty string.
(If the environment variable is unset or set to the empty string then the default colors will still be used.)
This builds on the work of https://github.com/scalameta/munit/pull/651 but attempts to minimize the size of the patch.

Honor the NO_COLOR environment variable.

---

build.sbt

I merged the update for mdoc, which uses Java 11, but that is needed to publish the website. It seems the normal release tries to publish docs and that breaks because of the mdoc JVM requirement.
This should fix the release.

chore: Don't publish the docs module

---

munit/shared/src/main/scala/munit/Assertions.scala

Small fix to improve failure message of `assertNotEquals` following @zaclegarssure suggestion.

fix #712: improve assertNotEquals failure message

---

munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/FixtureOrderFrameworkSuite.scala
tests/shared/src/test/scala/munit/SuiteLocalFixtureSuite.scala

:warning: **Breaking Change** :warning: 
This PR changes the ordering in which suite-local fixture `afterAll` methods are called.
It implements the trick @olafurpg describes in https://github.com/scalameta/munit/issues/573#issuecomment-1465269356 to restore the fixture ordering of v0.7.x
This ordering was changed in the [first v1.0 milestone release](https://github.com/scalameta/munit/releases/tag/v1.0.0-M1)
Therefore it is a breaking change within the v1.0 milestones in order to avoid a breaking change between v0.7.x and v1.0 overall.
Namely, we split up the suite-local fixture implementation into two fixtures, one of the `before*` methods, and one for the `after*` methods. Then we explicitly order `munitFixtures` to have the befores up front and the afters at the end.
Of particular …

Restore v0.7.x fixture ordering

---

munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala

This seems to fix issues with https://github.com/scalameta/munit/issues/711

improvement: Add transparent to compileErrors

---

munit/shared/src/main/scala/munit/Assertions.scala
tests/shared/src/test/scala/munit/FailExceptionSuite.scala

When trying to `intercept` an `AssertionError` till now the test passed successfully. 
This fix treats the FailException special.
closes: #679

fix intercept for AssertionError

---

build.sbt
project/plugins.sbt
tests/shared/src/test/scala/munit/AssertionsSuite.scala

Fixes https://github.com/scalameta/munit/issues/760

chore: Update scala native to 0.5.1

---

munit/js/src/main/scala/munit/internal/PlatformCompat.scala
munit/jvm/src/main/scala/munit/internal/PlatformCompat.scala

Changing the type of `munitTimeout` from `Duration` to `FiniteDuration` would be a breaking change, so we need to accept that durations can be infinite.
Fixes #572

Handle infinite timeouts

---

docs/getting-started.md
docs/integrations/external-integrations.md
docs/tests.md

* mention that IntelliJ Junit Plugin is required
* describe how to configure Maven
* update platform table
* add munit-scalacheck to integrations
Fixes #107
Fixes #345

Documentation updates

---

munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/Issue497FrameworkSuite.scala

These changes make munit print only the test suite names of suites for which it actually ran tests, rather than printing all suite names (even those for which all tests are being filtered out), as it's been doing up to now.
For example, instead of printing things like
```text
$ ./mill -i -w scala.integration.test "almond.integration.KernelTestsSimple3.completion"
…
almond.integration.KernelTestsSimple3:
+ completion 17.073s
almond.integration.KernelTestsTwoStepStartup3:
almond.integration.KernelTestsSimple213:
almond.integration.KernelTestsTwoStepStartup212:
almond.integration.KernelTestsTwoStepStartup213:
almond.integration.KernelTestsSimple212:
```
it now prints
```text
$ ./mill -i -w scala.integration.test "almond.integration.KernelTestsSimple3.completion"
… …
```

Don't print test suite name if no test is being run

---

munit/shared/src/main/scala/munit/FailExceptionLike.scala
munit/shared/src/main/scala/munit/TestTransforms.scala
tests/shared/src/main/scala/munit/TestTransformFrameworkSuite.scala

This should make it easier to write integrations.
Related: #817

Add a TestTransform to append to a failure message

---

munit/js/src/main/scala/munit/internal/io/Files.scala
munit/js/src/main/scala/munit/internal/io/PlatformIO.scala
munit/jvm/src/main/scala/munit/internal/io/PlatformIO.scala
munit/native/src/main/scala/munit/internal/io/PlatformIO.scala
munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala
munit/shared/src/main/scala/munit/internal/MacroCompatScala2.scala
munit/shared/src/main/scala/munit/internal/console/Lines.scala
tests/shared/src/main/scala/munit/AssertionsFrameworkSuite.scala
tests/shared/src/main/scala/munit/AsyncFunFixtureFrameworkSuite.scala
tests/shared/src/main/scala/munit/BoxedFrameworkSuite.scala
tests/shared/src/main/scala/munit/CiOnlyFrameworkSuite.scala
tests/shared/src/main/scala/munit/DiffProductFrameworkSuite.scala
tests/shared/src/main/scala/munit/DuplicateNameFrameworkSuite.scala
tests/shared/src/main/scala/munit/FailFrameworkSuite.scala
tests/shared/src/main/scala/munit/FailSuiteFrameworkSuite.scala
tests/shared/src/main/scala/munit/Issue179FrameworkSuite.scala
tests/shared/src/main/scala/munit/StackTraceFrameworkSuite.scala
tests/shared/src/test/scala/munit/LinesSuite.scala

Fixes https://github.com/scalameta/munit/issues/382
The `Location` macro currently captures the absolute path of the source file, which is not hermetic, and won't cache correctly on remote cached build tools such as Bazel, Gradle, and (in development) sbt 2.x.
```diff
$ jardiff target/out/jvm/scala-3.4.2/inctest/test-backend/ ../inctest2/target/out/jvm/scala-3.4.2/inctest/test-backend/
diff --git a/example/CowTest.class.asm b/example/CowTest.class.asm
index 1b3911e..91fd219 100644
--- a/example/CowTest.class.asm
+++ b/example/CowTest.class.asm
@@ -56,7 +56,7 @@
]
NEW munit/Location
DUP
-    LDC "/Users/xxx/work/inctest/src/test/scala/example/CowTest.scala"
+    LDC "/Users/xxx/work/inctest2/src/test/scala/example/CowTest.scala"
BIPUSH 6
INVOKESPECIAL munit/Location.<init> …
```

Fix Location macro to be hermetic

---

docs/getting-started.md

It is a simple change that remove Stability section of the documentation because project is now published with v1.x tags.

Remove Stability section because v1.x was released

---

docs/fixtures.md
docs/tests.md
munit-diff/shared/src/main/scala/munit/diff/Printer.scala

Fix some trivial hygiene diffs.

Fix documentation typos

---

docs/getting-started.md
docs/scalatest.md
docs/tests.md
junit-interface/src/main/java/munit/internal/junitinterface/EventDispatcher.java
junit-interface/src/main/java/munit/internal/junitinterface/PendingCommentTag.java
junit-interface/src/main/java/munit/internal/junitinterface/PendingTag.java
munit/js-native/src/main/scala/munit/internal/junitinterface/JUnitReporter.scala
munit/js-native/src/main/scala/munit/internal/junitinterface/MUnitRunNotifier.scala
munit/js-native/src/main/scala/munit/internal/junitinterface/PendingCommentTag.scala
munit/js-native/src/main/scala/munit/internal/junitinterface/PendingTag.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala
munit/shared/src/main/scala/munit/TestOptions.scala
munit/shared/src/main/scala/munit/TestValues.scala
munit/shared/src/main/scala/munit/package.scala
tests/shared/src/main/scala/munit/SkippedFrameworkSuite.scala

- Also show elapsed time for JS/Native Ignored tests (may be non-zero), to be consistent with JVM

Support “Pending” test case Tag #839

---

munit/shared/src/main/scala/munit/Assertions.scala
tests/shared/src/main/scala/munit/StackTraceFrameworkSuite.scala

Not sure why not show the stack trace and it's rather unexpected
Fixes https://github.com/scalameta/munit/issues/782
Opinions @valencik @mzuehlke ?

bugfix: Print stack trace for assertEquals

---

munit/js-native/src/main/scala/munit/internal/junitinterface/JUnitReporter.scala
munit/native/src/main/scala/munit/internal/PlatformCompat.scala
tests/shared/src/main/scala/munit/BaseFrameworkSuite.scala
tests/shared/src/main/scala/munit/Issue285FrameworkSuite.scala
tests/shared/src/main/scala/munit/SkippedFrameworkSuite.scala

Since Scala Native 0.5.0 we have access to multithreading support, it's enabled by default if we detect usage of threading in the compiled code. This change does acknowledge multihreading support in PlatformCompat for Native (mostly copy-paste based on JVM implementation with minor changes) 
Additional changes required to unsupress `Issue285FrameworkSuite`: 
- Don't print stacktrace of the uncought exception - it's not reported on the JVM. Make the outputs of JVM and JS/Native compliant 
- Handle optional possible extra space before `<elapsed time>` pattern - it is sometimes produced by the JVM 
- Print elapased time milliseconds using 3 digits instead of 2 (to follow JVM semantics)

Support Scala Native multithreading

---

build.sbt

This avoids building e.g. IgnoreSuite targeting the latest class file version supported by the JDK used at build time.
https://github.com/scalameta/munit/issues/868

Consider a -source and -target version for javac

---

munit-diff/shared/src/main/scala/munit/diff/Diff.scala
tests/shared/src/main/scala/munit/AssertionsFrameworkSuite.scala
tests/shared/src/main/scala/munit/DiffProductFrameworkSuite.scala
tests/shared/src/main/scala/munit/Issue179FrameworkSuite.scala
tests/shared/src/main/scala/munit/StackTraceFrameworkSuite.scala
tests/shared/src/main/scala/munit/TestTransformFrameworkSuite.scala
tests/shared/src/test/scala/munit/ComparisonFailExceptionSuite.scala
tests/shared/src/test/scala/munit/DiffsSuite.scala

It was mapping obtained to original, and expected to revised.

Diff: swap the order of expected-vs-obtained

---

munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/Compare.scala

Part 1 of 2 in modifying assert failure output.

Compare: use implicit Location

---

docs/tests.md
munit-diff/shared/src/main/scala/munit/diff/Diff.scala
munit-diff/shared/src/main/scala/munit/diff/DiffOptions.scala
munit-diff/shared/src/main/scala/munit/diff/Diffs.scala
munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/Compare.scala
munit/shared/src/main/scala/munit/Diffs.scala
tests/shared/src/main/scala/munit/Issue179FrameworkSuite.scala
tests/shared/src/main/scala/munit/StackTraceFrameworkSuite.scala
tests/shared/src/test/scala/munit/DiffsSuite.scala

Sets diff context size and optionally outputs line offsets. This is part 2, following #881. Builds upon #788.

Diff: add new DiffOptions parameter

---

build.sbt
munit-diff/shared/src/main/scala/munit/diff/Diff.scala
munit-diff/shared/src/main/scala/munit/diff/DiffOptions.scala
munit-diff/shared/src/main/scala/munit/diff/console/AnsiColors.scala
munit/shared/src/main/scala/munit/Assertions.scala
munit/shared/src/main/scala/munit/SuiteTransforms.scala
munit/shared/src/main/scala/munit/internal/console/Lines.scala
project/Mima.scala
tests/shared/src/test/scala/munit/DiffsSuite.scala

Also, exclude `munit.internal.` from MIMA.

DiffOptions: allow controlling use of ANSI markers

---

munit/js-native/src/main/scala/munit/internal/junitinterface/JUnitReporter.scala
tests/js/src/test/scala/munit/DurationJSSuite.scala

When running on Scala.js, if duration associated with the test event is available, bubble it up through the SBT's test interface using the slot dedicated to just such information: sbt.testing.Event.duration.
In addition to it being a shame to throw away information about the duration that is literally in our hands, this avoids weird-looking negative duration values in test reports.

Populate sbt.testing.Event.duration on Scala.js

---

docs/integrations/scalacheck.md

The displayed version in the website is `1.0.4` (a.k.a `STABLE_VERSION`) which doesn't even exist

Fix munit-scalacheck version

---

munit/shared/src/main/scala/munit/MUnitRunner.scala

Previously, since `.map` was used on the resulting future, this step may have been skipped.
Instead, refactor `runTest` a little to handle errors and Finished flag correctly.

MunitRunner: make sure to call fireTestFinished

---

munit/shared/src/main/scala/munit/MUnitRunner.scala

We need to run the closing step even if the future executing the tests results in a failure.

MunitRunner: run afterAll if beforeAll didn't fail

---

munit/shared/src/main/scala-2.13/munit/internal/Compat.scala
munit/shared/src/main/scala-3/munit/internal/Compat.scala
munit/shared/src/main/scala-pre-2.13/munit/internal/Compat.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala

There's no need to persist the values in the LazyList when they are not going to be reused.

MunitRunner: use simple Iterator, not LazyList

---

munit/shared/src/main/scala/munit/MUnitRunner.scala

Currently, if a future returns a failure, due to use of `.flatMap` we would stop collecting results of further futures and fail.

MunitRunner: sequenceFutures: continue on failure

---

munit/js/src/main/scala/munit/internal/PlatformCompat.scala
munit/native/src/main/scala/munit/internal/PlatformCompat.scala
munit/shared/src/main/scala/munit/MUnitRunner.scala

Since the `val suite` was being initialized non-lazily, there's no real reason to pass a function.

MUnitRunner: take a suite in the constructor

---

docs/getting-started.md

FYI: On https://scalameta.org/munit/ front page, a link to the image for "IDE support" is broken.

Mention Gradle plugin for Scala.js and Scala Native

---

munit/shared/src/main/scala/munit/MUnitRunner.scala
tests/shared/src/main/scala/munit/AfterEachExceptionSuite.scala
tests/shared/src/test/scala/munit/FrameworkSuite.scala

This should fix the issue in #966. I couldn't figure out how to write a test for it. Someone should probably do that before merging to make sure that it works as expected.

Do not swallow exceptions in afterEach. Fixes #966
